<a href="https://colab.research.google.com/github/IvanKatorgin/math-for-DS/blob/main/%D0%94%D0%BE%D0%BF%D0%BE%D0%BB%D0%BD%D0%B8%D1%82%D0%B5%D0%BB%D1%8C%D0%BD%D0%BE%D0%B5_%D0%B4%D0%BE%D0%BC%D0%B0%D1%88%D0%BD%D0%B5%D0%B5_%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Домашнее задание "Основные математические понятия".

## Уровень 0:


Представим фильмы в виде бинарных векторов (numpy array) используя следующие признаки:

[Комедия, Боевик, Исторический, Бред Питт, Бенедикт Камбербэтч, Квентин Тарантино]

[Игра в имитацию](https://www.kinopoisk.ru/film/635772/)

[Ярость](https://www.kinopoisk.ru/film/740644/)

[12 лет рабства](https://www.kinopoisk.ru/film/606646/)

[Однажды в Голливуде](https://www.kinopoisk.ru/film/1047883/)

```
film_1 = np.array([0,0,0,0,1,0])      # Игра в имитацию

film_2 = np.array([0,1,0,1,0,0])      # Ярость

film_3 = np.array([0,0,1,1,1,0])      # 12 лет рабства

film_4 = np.array([1,0,0,1,0,1])      # Однажды в Голливуде
```



In [ ]:
### YOUR CODE HERE

In [ ]:
import pandas as pd, numpy as np

In [ ]:
film_1 = np.array([0,0,0,0,1,0])      # Игра в имитацию
film_2 = np.array([0,1,0,1,0,0])      # Ярость
film_3 = np.array([0,0,1,1,1,0])      # 12 лет рабства
film_4 = np.array([1,0,0,1,0,1])      # Однажды в Голливуде

### Задание 1

Найти угол между векторами-фильмами "Ярость" и "12 лет рабства". Результатом будет являться косинусная мера, которую можно использовать для определения похожести векторов.

In [ ]:
### YOUR CODE HERE

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
# длины векторов
film_2_Length = np.linalg.norm(film_2)
film_3_Length = np.linalg.norm(film_3)

cos = np.dot(film_2, film_3) / (film_2_Length * film_3_Length)
cos

0.40824829046386296

In [ ]:
# найдем угол
import math
angle = round(math.degrees(math.acos(cos)), 2)
angle

65.91

## Уровень 1:

### Задание 2

Вычислить с помощью Python значение первой производной для функции $8x(x+3)^2$ в точке $x=1$


In [ ]:
### YOUR CODE HERE

In [ ]:
from sympy import *

In [ ]:
x = Symbol('x')

In [ ]:
y = 8*x*((x+3)**2)

In [ ]:
yprime = y.diff(x)
yprime

8*x*(2*x + 6) + 8*(x + 3)**2

In [ ]:
yprime.subs(x, 1).evalf()

192.000000000000

In [ ]:
# можно еще и так
f = lambdify(x, yprime, 'numpy')
f(np.ones(1))

array([192.])

### Задание 3


Объединить векторы фильмов в матрицу, где каждый вектор является строкой матрицы. Умножьте вектор [1,2,3,4] на полученную матрицу

In [ ]:
### YOUR CODE HERE

In [ ]:
#film_all = np.concatenate([[film_1], [film_2], [film_3], [film_4]])
film_all = np.array([film_1, film_2, film_3, film_4])
film_all

array([[0, 0, 0, 0, 1, 0],
       [0, 1, 0, 1, 0, 0],
       [0, 0, 1, 1, 1, 0],
       [1, 0, 0, 1, 0, 1]])

In [ ]:
# горизонтальный вектор
v = np.array([1,2,3,4])
v

array([1, 2, 3, 4])

In [ ]:
# горизонтальный вектор. вариант 1
res = film_all.T @ v
res

array([4, 2, 3, 9, 4, 4])

In [ ]:
# горизонтальный вектор. вариант 2
res = film_all.T.dot(v)
res

array([4, 2, 3, 9, 4, 4])

In [ ]:
# горизонтальный вектор. вариант 3
res = v @ film_all
res

array([4, 2, 3, 9, 4, 4])

In [ ]:
# горизонтальный вектор. вариант 4
res = v.dot(film_all)
res

array([4, 2, 3, 9, 4, 4])

In [ ]:
# вертикальный вектор
vec = [[1],
       [2],
       [3],
       [4]]
vec = np.array(vec)
vec

array([[1],
       [2],
       [3],
       [4]])

In [ ]:
# вертикальный вектор. вариант 1
res = film_all.T @ vec
res

array([[4],
       [2],
       [3],
       [9],
       [4],
       [4]])

In [ ]:
# вертикальный вектор. вариант 2
res = film_all.T.dot(vec)
res

array([[4],
       [2],
       [3],
       [9],
       [4],
       [4]])

In [ ]:
# вертикальный вектор. вариант 3
res = vec.T @ film_all
res

array([[4, 2, 3, 9, 4, 4]])

In [ ]:
# вертикальный вектор. вариант 4
res = vec.T.dot(film_all)
res

array([[4, 2, 3, 9, 4, 4]])