<a href="https://colab.research.google.com/github/IvanKatorgin/math-for-DS/blob/main/%D0%9C%D0%B0%D1%82%D0%B5%D0%BC%D0%B0%D1%82%D0%B8%D0%BA%D0%B0_%D0%B4%D0%BB%D1%8F_DS_%D0%B4%D0%BE%D0%BC%D0%B0%D1%88%D0%BD%D0%B5%D0%B5_%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Курс "Математика для Data Science". Домашнее задание 1. Линейная алгебра. Матрицы. Каторгин И.П.

Уровень 0:

Задание 1

- Создайте матрицу 3 на 3, заполненную числами от 1 до 9
- Прибавьте к ней матрицу с единицами на диагонале
- Умножьте полученную матрицу на вектор (1, 2, 3)
- Вычислить транспонированную матрицу $A^T$ от полученной в результате прибавления матрицы
- Посчитайте обратную матрицу к полученной в результате прибавления матрице

In [ ]:
import numpy as np, sympy as sp, sklearn as skl

Создайте матрицу 3 на 3, заполненную числами от 1 до 9

In [ ]:
A1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
A1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Прибавьте к ней матрицу с единицами на диагонале

In [ ]:
A2 = np.diag(np.full(3,1))
A2

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [ ]:
d1 = np.eye(3) # можно и так задать
d1

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
A3 = A1 + A2
A3

array([[ 2,  2,  3],
       [ 4,  6,  6],
       [ 7,  8, 10]])

Умножьте полученную матрицу на вектор (1, 2, 3)

In [ ]:
vec = np.array([1, 2, 3])
vec

array([1, 2, 3])

In [ ]:
A4 = A3 @ vec # вариант 1
A4

array([15, 34, 53])

In [ ]:
A5 = A3.dot(vec) # вариант 2
A5

array([15, 34, 53])

Вычислить транспонированную матрицу  $A^T$  от полученной в результате прибавления матрицы

In [ ]:
A6 = np.transpose(A3)
A6

array([[ 2,  4,  7],
       [ 2,  6,  8],
       [ 3,  6, 10]])

Посчитайте обратную матрицу к полученной в результате прибавления матрице

In [ ]:
A7 = np.linalg.inv(A6)
A7

array([[-6. , -1. ,  5. ],
       [-2. ,  0.5,  1. ],
       [ 3. ,  0. , -2. ]])

In [ ]:
# проверка
A6 @ A7

array([[ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  1.00000000e+00,  0.00000000e+00],
       [-3.55271368e-15,  0.00000000e+00,  1.00000000e+00]])

Уровень 1:

Задание 2

Найдите собственные значения и собственные вектора матрицы:

m = np.array([[2, 2],
              [1, 3]])

print(m)

In [ ]:
m = np.array([[2, 2], [1, 3]])
print(m)

[[2 2]
 [1 3]]


In [ ]:
# собственное значение
np.linalg.eigvals(m)

array([1., 4.])

In [ ]:
# собственное значение и собственный вектор
res = np.linalg.eig(m)
res

EigResult(eigenvalues=array([1., 4.]), eigenvectors=array([[-0.89442719, -0.70710678],
       [ 0.4472136 , -0.70710678]]))

In [ ]:
res2 = res[1]
res2

array([[-0.89442719, -0.70710678],
       [ 0.4472136 , -0.70710678]])

In [ ]:
res3 = np.transpose(res2)

In [ ]:
res3[0]

array([-0.89442719,  0.4472136 ])

In [ ]:
res3[1]

array([-0.70710678, -0.70710678])

Задание 3

Придумайте матрицу, у которой определитель = 1, и все элементы не равны 0.

P.S. Матрица должна быть ненулевой и размерностью не менее 2!

In [ ]:
ad - bc = 1
ad > bc на 1

In [ ]:
n = np.array([[4, 3], [1, 1]])
print(n)

[[4 3]
 [1 1]]


In [ ]:
# вычисляем определитель
np.linalg.det(n)

1.0